{% set name = "pgmpy" %}
{% set version = "0.1.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pgmpy-{{ version }}.tar.gz
  sha256: b1c3861f13142e507b6d122f32433663c85e9992528dd245872dd7b415c1dff3

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - networkx
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - pyparsing
    - pytorch
    - statsmodels
    - tqdm
    - joblib

test:
  imports:
    - pgmpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pgmpy/pgmpy
  summary: A library for Probabilistic Graphical Models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JohanMabille
