{% set name = "pgmpy" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pgmpy-{{ version }}.tar.gz
  sha256: a62a89352f139a5d459839e54e6bfa202a7d8749e6dc6d7ceec088a71529af45

build:
  skip: true  # [py<310 or py>=314]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - huggingface_hub >=0.23
    - networkx >=3.0
    - numpy >=2.0
    - scipy >=1.10
    - scikit-learn >=1.2
    - pandas >=1.5
    - statsmodels >=0.14.5
    - tqdm >=4.64
    - pyparsing >=3.0
    - joblib >=1.2
    - opt_einsum >=3.3
    - scikit-base >=0.12.4

test:
  imports:
    - pgmpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.pgmpy.org
  summary: Python Toolkit for Causal and Probabilistic Reasoning
  license: MIT
  license_file: LICENSE
  doc_url: https://www.pgmpy.org
  dev_url: https://github.com/pgmpy/pgmpy

extra:
  recipe-maintainers:
    - ankurankan
    - JohanMabille
