{% set name = "pgmpy" %}
{% set version = "0.1.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pgmpy-{{ version }}.tar.gz
  sha256: 90e9abf636629b6c1528df5847d2861b06220d103b5da414fcc74df0ee94cbf1

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python
    - pip
  run:
    - python
    - networkx
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - pyparsing
    - pytorch
    - statsmodels
    - tqdm
    - joblib

test:
  imports:
    - pgmpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pgmpy/pgmpy
  summary: A library for Probabilistic Graphical Models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JohanMabille
