{% set name = "pgmpy" %}
{% set version = "0.1.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pgmpy-{{ version }}.tar.gz
  sha256: de8096175a8417f6bbac4e6ddb4a253c824947697d7beed93266d6e4163d039e

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - networkx
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - pyparsing
    - pytorch
    - statsmodels
    - tqdm
    - joblib

test:
  imports:
    - pgmpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pgmpy/pgmpy
  summary: A library for Probabilistic Graphical Models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ankurankan
    - JohanMabille
