{% set name = "pgmpy" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pgmpy-{{ version }}.tar.gz
  sha256: 4f6e3b79327f02cad7fb3c3fa1047b42ecbbd80f02be299946e13bb803f76fb8

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - networkx
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - pyparsing
    - pytorch
    - statsmodels
    - tqdm
    - joblib

test:
  imports:
    - pgmpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pgmpy/pgmpy
  summary: A library for Probabilistic Graphical Models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ankurankan
    - JohanMabille
